config/routes.rb
VRP::Application.routes.draw do
  
  get "videos/vr/:id" => 'videos#showVR', as: :showVR
  get "videos/demo" => 'videos#demo', as: :demo
  resources :videos, only:[:index, :show]

  root 'videos#welcome'

end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

	def welcome
	end

  def index
  	@videos = Video.all
  end

  def show
  	@video = Video.find(params[:id])
  end

  def showVR
  	@video = Video.find(params[:id])
  end

  def demo

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VRP</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= yield %>
</body>
</html>

app/views/videos/demo.html.erb
<nav class="container">
  <div class="demo-navbar">
    <div class="col-lg-1"></div>
    <div class="col-lg-11">
      <div class="brand">
        WeMakeVRPorn.com
      </div>
      <div class="tagline">
        Truly Hands Free Enjoyment
      </div>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row" id="hotchick">
    <%= image_tag("HotGirl.jpg", width: "80%") %>
    <%= image_tag("OculusRift.png", width: "50%", id: "oculus-image") %>
  </div>
  <div class="row offer">
    <div class="col-lg-10 offer-text">
      SPECIAL LAUNCHING OFFER - Complete Access For Only $9.99 
    </div>
    <div class="col-lg-2 offer-button">
      <%= link_to "Try Me", videos_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>

<div class="container demo-container">
  <div class="row demo-title">
    Over the Kitchen Table with Sara
  </div>
  <div class="row demo-content">
    <div class="col-lg-9">
      <div class="row">
        video here
      </div>
      <div class="row">
        <div class="demo-video-links">
          regular video
        </div>
        <div class="demo-video-links">
          vr video
        </div>
      </div>
    </div>
    <div class="col-lg-3">
    </div>
  </div>
</div>

<div class="container demo-container">
  <div class="row demo-title">
    Over the Kitchen Table with Sara
  </div>
  <div class="row demo-content">
    <div class="col-lg-9">
      <div class="row">
        video here
      </div>
      <div class="row">
        <div class="demo-video-links">
          regular video
        </div>
        <div class="demo-video-links">
          vr video
        </div>
      </div>
    </div>
    <div class="col-lg-3">
    </div>
  </div>
</div>

<div class="container demo-container">
  <div class="row demo-title">
    Over the Kitchen Table with Sara
  </div>
  <div class="row demo-content">
    <div class="col-lg-9">
      <div class="row">
        video here
      </div>
      <div class="row">
        <div class="demo-video-links">
          regular video
        </div>
        <div class="demo-video-links">
          vr video
        </div>
      </div>
    </div>
    <div class="col-lg-3">
    </div>
  </div>
</div>

<div class="container demo-container">
  <div class="row demo-title">
    Over the Kitchen Table with Sara
  </div>
  <div class="row demo-content">
    <div class="col-lg-9">
      <div class="row">
        video here
      </div>
      <div class="row">
        <div class="demo-video-links">
          regular video
        </div>
        <div class="demo-video-links">
          vr video
        </div>
      </div>
    </div>
    <div class="col-lg-3">
    </div>
  </div>
</div>

<div class="container">
  <div class="row offer">
    <div class="col-lg-10 offer-text">
      SPECIAL LAUNCHING OFFER - Complete Access For Only $9.99 
    </div>
    <div class="col-lg-2 offer-button">
      <%= link_to "Try Me", videos_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
  <div class="row testimony">
    <div class="col-lg-6">
      <div class="row">
        <fieldset>
          "Oh Man!!  Ever since I bought the Oculus I KNEW this day was coming.  I beat off so hard.  My toe nails shot off through my socks!"
        </fieldset>
      </div>
      <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
          Joe Blow<br>
          Master Beta Tester
        </div>
        <div class="col-lg-2">

        </div>
        <div class="col-lg-1"></div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="row">
        <fieldset>
          "Oh Man!!  Ever since I bought the Oculus I KNEW this day was coming.  I beat off so hard.  My toe nails shot off through my socks!"
        </fieldset>
      </div>
      <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
          Joe Blow<br>
          Master Beta Tester
        </div>
        <div class="col-lg-2">

        </div>
        <div class="col-lg-1"></div>
      </div>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">OCULUST</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">CATEGORIES <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">POV</a></li>
            <li><a href="#">LESBIAN</a></li>
            <li><a href="#">COLLEGE</a></li>
            <li><a href="#">MASTURBATION</a></li>
            <li><a href="#">DONKEY SHOWS</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <li><a href="#">Contact Us</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">BigWang69<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">EDIT PROFILE</a></li>
            <li><a href="#">ACCOUNT</a></li>
            <li><a href="#">LOG OUT</a></li>
            <li class="divider"></li>
            <li><a href="#">GIVE US FEEDBACK</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- body of page -->
<div class="row">
	<div class="col-md-1 col-lg-1"></div>
	<!-- main content goes here -->
	<div class="col-md-10 col-lg-10">
		<h3>Featured Videos</h3>
		<fieldset>
			<% @videos.each do |v| %>
				<div class="col-md-4 previews">
					<p><%= image_tag v.url %></p>
					<h5><%= v.name %></h5>
					<p>
						<%= link_to "Watch It Now", video_path(v), class: "btn btn-warning" %>
						<%= link_to "Watch VR Version", showVR_path(v), class: "btn btn-danger" %>
					</p>
				</div>
			<% end %>
		</fieldset>
	</div>
	<div class="col-md-1 col-lg-1"></div>
</div>

app/views/videos/show.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">OCULUST</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">CATEGORIES <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">POV</a></li>
            <li><a href="#">LESBIAN</a></li>
            <li><a href="#">COLLEGE</a></li>
            <li><a href="#">MASTURBATION</a></li>
            <li><a href="#">DONKEY SHOWS</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <li><a href="#">Contact Us</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">BigWang69<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">EDIT PROFILE</a></li>
            <li><a href="#">ACCOUNT</a></li>
            <li><a href="#">LOG OUT</a></li>
            <li class="divider"></li>
            <li><a href="#">GIVE US FEEDBACK</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- body of page -->
<div class="row">
	<div class="col-md-1 col-lg-1"></div>
	<!-- main content goes here -->
	<div class="col-md-10 col-lg-10">
		<%= video_tag "Video#{@video.num}.mp4", size: "1024x768", controls: true %>
	</div>
	<div class="col-md-1 col-lg-1"></div>
</div>

app/views/videos/showVR.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">OCULUST</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">CATEGORIES <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">POV</a></li>
            <li><a href="#">LESBIAN</a></li>
            <li><a href="#">COLLEGE</a></li>
            <li><a href="#">MASTURBATION</a></li>
            <li><a href="#">DONKEY SHOWS</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <li><a href="#">Contact Us</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">BigWang69<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">EDIT PROFILE</a></li>
            <li><a href="#">ACCOUNT</a></li>
            <li><a href="#">LOG OUT</a></li>
            <li class="divider"></li>
            <li><a href="#">GIVE US FEEDBACK</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<!-- body of page -->
<div class="row">
	<!-- main content goes here -->
	<div class="main">
		<%= video_tag "Video#{@video.num}.mp4", size: "1052x768", autoplay: true, id: "vrmain" %><br>
		<div id="video1"><canvas id="vr1" width="602" height="768"></canvas></div>
		<div id="video2"><canvas id="vr2" width="602" height="768"></canvas></div>
	</div>
</div>

app/views/videos/welcome.html.erb
<div class="row">
	<div class="col-md-1 col-lg-1"></div>


	<div class="col-md-10 col-lg-10">
	<h1 id="welcomeLogo">Logo Goes Here</h1>
	</div>


	<div class="col-md-1 col-lg-1"></div>
</div>

<div class="row">
	<div class="col-md-1 col-lg-1"></div>


	<div class="col-md-10 col-lg-10">
		<div class="col-md-3 col-lg-3"></div>
			<div class="col-md-6 col-lg-6">
				<h3>Terms of Agreement</h3>
				<div class="terms">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
				</div>
				<form id="welcomeValidation" onsubmit="welcomeFormValidation()">
					<input type="checkbox" id="agree"> I have read and agree to these terms.
					<div class="btn btn-danger" onclick="welcomeFormValidation()">ENTER</div>
				</form>
				
			</div>

		<div class="col-md-3 col-lg-3"></div>
	</div>


	<div class="col-md-1 col-lg-1"></div>
</div>